config/routes.rb
Rails.application.routes.draw do
  #get 'dashboard/index'
  get 'dashboard', to: 'dashboard#index'
  namespace :dashboard do
    resources :products, except: %i[show]
    resources :users, except: %i[show]
    resources :employees, except: %i[show]
    resources :cities, except: %i[show]
    resources :carousels, except: %i[show]
    resources :pages, except: %i[show new destroy]
    resources :lines, except: %i[show new destroy]
    resources :brands, except: %i[show]
  end

  devise_for :users, :skip => [:registration]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carousel.rb
class Carousel < ApplicationRecord
    validates :description, :image, presence: true
    has_one_attached :image
end

app/controllers/dashboard/brands_controller.rb
class Dashboard::BrandsController < DashboardController
  before_action :set_brand, only: %i[edit update destroy]
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(params_brand)
    if @brand.save
      redirect_to dashboard_brands_path, notice: "Marca #{@brand.description} cadastrada com sucesso"
    else
      flash.now[:alert] = @brand.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit

  end

  def update
    if @brand.update(params_brand)
      redirect_to dashboard_brands_path, notice: "Marca #{@brand.description} atualizada com sucesso"
    else
      flash.now[:alert]= @brand.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @brand.destroy
      redirect_to dashboard_brands_path, notice: "Marca #{@brand.description} excluido com sucesso"
    else
      flash.now[:alert]= @brand.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end

  def params_brand
    params.require(:brand).permit(:description, :line_id, :image)
  end
end

app/controllers/dashboard/carousels_controller.rb
class Dashboard::CarouselsController < DashboardController
  before_action :set_carousel, only: %i[edit update destroy]
  def index
    @carousels = Carousel.all
  end

  def new
    @carousel = Carousel.new
  end

  def create
    @carousel = Carousel.new(params_carousel)
    if @carousel.save
      redirect_to dashboard_carousels_path, notice: "Destaque #{@carousel.description} cadastrado com sucesso"
    else
      flash.now[:alert]= @carousel.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit

  end

  def update
    if @carousel.update(params_carousel)
      redirect_to dashboard_carousels_path, notice: "Destaque #{@carousel.description} atualizado com sucesso"
    else
      flash.now[:alert]= @carousel.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @carousel.destroy
      redirect_to dashboard_carousels_path, notice: "Destaque #{@carousel.description} excluido com sucesso"
    else
      flash.now[:alert]= @carousel.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_carousel
    @carousel = Carousel.find(params[:id])
  end

  def params_carousel
    params.require(:carousel).permit(:description, :image)
  end
end

app/controllers/dashboard/cities_controller.rb
class Dashboard::CitiesController < DashboardController
  before_action :set_city, only: %i[edit update destroy]
  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(params_city)
    if @city.save
      redirect_to dashboard_cities_path, notice: "A cidade #{@city.description} cadastrada com sucesso!"
    else
      flash.now[:alert] = @city.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @city.update(params_city)
      redirect_to dashboard_cities_path, notice: "A cidade  #{@city.description} atualizada com sucesso!"
    else
      flash.now[:alert] = @city.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @city.destroy
      redirect_to dashboard_cities_path, notice: "A cidade  #{@city.description} excluida com sucesso!"
    else
      flash.now[:alert] = @city.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_city
    @city = City.find(params[:id])
  end

  def params_city
    params.require(:city).permit(:description, :employee_id)
  end
end

app/controllers/dashboard/employees_controller.rb
class Dashboard::EmployeesController < DashboardController
  before_action :set_employee, only: %i[edit update destroy]
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(params_employee)
    if @employee.save
      redirect_to dashboard_employees_path, notice: "O funcionario #{@employee.fullname} cadastrado com sucesso"
    else
      flash.now[:alert]= @employee.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit

  end

  def update
    if @employee.update(params_employee)
      redirect_to dashboard_employees_path, notice: "O funcionario #{@employee.fullname} atualizado com sucesso"
    else
      flash.now[:alert]= @employee.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @employee.destroy
      redirect_to dashboard_employees_path, notice: "O funcionario #{@employee.fullname} excluido com sucesso"
    else
      flash.now[:alert]= @employee.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def params_employee
    params.require(:employee).permit(:fullname, :cellphone)
  end
end

app/controllers/dashboard/lines_controller.rb
class Dashboard::LinesController < DashboardController
  before_action :set_line, only: %i[edit update]
  def index
    @lines = Line.all
  end

  def edit

  end

  def update
    if @line.update(params_line)
      redirect_to dashboard_lines_path, notice: "Linha #{@line.description} atualizada com sucesso"
    else
      flash.now[:alert]= @line.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_line
    @line = Line.find(params[:id])
  end

  def params_line
    params.require(:line).permit(:description, :image)
  end
end

app/controllers/dashboard/pages_controller.rb
class Dashboard::PagesController < DashboardController
  before_action :set_page, only: %i[edit update]
  def index
    @pages = Page.first
  end

  def edit

  end

  def update
    if @page.update(params_page)
      redirect_to dashboard_pages_path, notice: "#{@page.title} atualizada com sucesso"
    else
      flash.now[:alert]= @page.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_page
    @page = Page.find(params[:id])
  end

  def params_page
    params.require(:page).permit(:title, :description, :image)
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < DashboardController
  before_action :set_product, only: %i[edit update destroy]
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params_product)
    if @product.save
      redirect_to dashboard_products_path, notice: "O Produto #{@product.description} cadastrada com sucesso"
    else
      flash.now[:alert] = @product.errors.full_messagess.to_sentence
      render :new
    end
  end

  def edit

  end

  def update
    if @product.update(params_product)
      redirect_to dashboard_products_path, notice: "O produto #{@product.description} atualizada com sucesso"
    else
      flash.now[:alert]= @product.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to dashboard_products_path, notice: "O produto #{@product.description} excluido com sucesso"
    else
      flash.now[:alert]= @product.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def params_product
    params.require(:product).permit(:description, :brand_id, :image)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < DashboardController
  before_action :set_user, only: %i[edit update destroy]
  before_action :allow_without_password, only: [:update]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} cadastrado com sucesso"
    else
      flash.now[:alert]= @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update(params_user)
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} atualizado com sucesso"
    else
      flash.now[:alert]= @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} excluido com sucesso"
    else
      flash.now[:alert]= @user.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def params_user
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  # remove o input da validação do devise
  def allow_without_password
    if  params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
        params[:admin].delete(:password)
        params[:admin].delete(:password_confirmation)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  def index
  end
end

app/helpers/dashboard/brands_helper.rb
module Dashboard::BrandsHelper
end

app/helpers/dashboard/carousels_helper.rb
module Dashboard::CarouselsHelper
end

app/helpers/dashboard/cities_helper.rb
module Dashboard::CitiesHelper
end

app/helpers/dashboard/employees_helper.rb
module Dashboard::EmployeesHelper
end

app/helpers/dashboard/lines_helper.rb
module Dashboard::LinesHelper
end

app/helpers/dashboard/pages_helper.rb
module Dashboard::PagesHelper
end

app/helpers/dashboard/products_helper.rb
module Dashboard::ProductsHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
    def toastr_flash_class(type)
        case type
        when "alert"
          "toastr.error"
        when "notice"
          "toastr.success"
        else
          "toastr.info"
        end
    end
end

app/views/dashboard/carousels/_form_carousels.html.erb
<div class="container">
        <h5 class="title-form text-center">
            <strong><%= action %></strong>
        </h5>

        <%= form_with(model: [:dashboard, @carousel],local: true, multipart: true) do |f| %>
            <div class="row">
                <div class="form-group col-md-6 offset-md-3">
                    <label>Título</label>
                    <%= f.text_field :description, type:"text", autofocus: true, class:"form-control", placeholder:"Kit Kat" %>
                </div>
                <div class="form-group col-md-6 offset-md-3">
                        <button type="button" class="btn btn-primary btn-block" onclick="document.getElementById('inputFile').click()">Add Image</button>
                        <div class="form-group inputDnD">
                          <label class="sr-only" for="inputFile">File Upload</label>
                          <%= f.file_field :image, type:"file", class:"form-control-file text-primary font-weight-bold", id:"inputFile", accept:"image/*", onchange:"readUrl(this)", data:{title:"Drag and drop a file"} %>
                        </div>
                    </div>
                </div>
                <div class="offset-md-5">
                    <%= f.submit btn_action, class:"btn btn-success" %>
                        <%= link_to "Cancelar", dashboard_carousels_path, class:"btn btn-danger" %>
                </div>
            </div>
        <% end %>
    </div>

app/views/dashboard/carousels/edit.html.erb
<%= render partial: "dashboard/shared/title", locals: {title: "Destaques"} %>
<%= render partial: "form_carousels", locals: {action: "Alterando destaque", btn_action: "Salvar"} %>

app/views/dashboard/carousels/index.html.erb
<%= render partial: "dashboard/shared/title", locals: {title: "Destaques"} %>
<% if @carousels.count >0 %>
    <%= link_to new_dashboard_carousel_path, class:"btn btn-success btn-center" do %>
        <i class="fa fa-plus">&nbsp; Cadastrar</i>
        <% end %>
            <hr>
        <table class="table table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Imagem</th>
                    <th scope="col" class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                <% @carousels.each do |carousel| %>
                    <tr>
                        <td class="align-middle">
                            <%= carousel.id %>
                        </td>
                        <td class="align-middle">
                            <%= carousel.description %>
                        </td>
                        <td>
                            <% if carousel.image.attached? %>
                                <%= image_tag carousel.image, class:"img-fluid image-mini" %>
                            <% else %>
                                <%= image_tag '/no_img.png', class:"card-img-top img-fluid image-mini" %>
                            <% end %>
                        </td>
                        <td class="text-center align-middle">
                            <%= link_to "Editar", edit_dashboard_carousel_path(carousel.id), class: "btn btn-primary" %>
                                <%= link_to "Excluir", dashboard_carousel_path(carousel.id), method: :delete,
                                                        data:{ confirm: "Tem certeza disso?" }, class:"btn btn-danger" %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% else %>
        <div class="alert alert-danger text-center" role="alert">
            <i class="fa fa-exclamation-triangle"> Sem destaque cadastrados! </i>
        </div>
        <%= link_to new_dashboard_carousel_path, class:"btn btn-success btn-center" do %>
            <i class="fa fa-plus">&nbsp; Cadastrar</i>
            <% end %>
        <% end %>

app/views/dashboard/carousels/new.html.erb
<%= render partial: "dashboard/shared/title", locals: {title: "Destaques"} %>
<%= render partial: "form_carousels", locals: {action: "Cadastrando destaque", btn_action: "Cadastrar"} %>